Working on animator CSS section, WIP
WICG/animation-worklet pull request #28
Opened 2017-03-28 14:15 UTC by stephenmcgruer

2017-03-28 14:16 UTC, stephenmcgruer commented
@flackr This is just an FYI atm, I'm working on improving the CSS notation section of the spec.

2017-04-04 19:08 UTC, stephenmcgruer commented
Ping for review?

2017-04-05 20:37 UTC, flackr requested changes

2017-04-05 20:37 UTC, flackr commented on Overview.bs
> +        exists, one is created with the document root element as it's <a>root element proxy</a>.
Except that I don't think we'll actually pass in a proxy for the document root. This should maybe just refer to the animator instance with no root element?

2017-04-06 14:59 UTC, flackr approved these changes

2017-04-06 14:59 UTC, flackr commented on Overview.bs
> +        exists, one is created with the document root element as it's <a>root element proxy</a>.
I've changed my mind on this one. Passing the root element is simple and easy to reason about.

2017-04-06 15:00 UTC, merged